### ISSUE TITLE
Response to your comment

### ISSUE THREAD

**Issue by guyluz11** [vijaykarthiktk/vijaykarthiktk#1]
Hi, I saw you commented on my report infinite_horizons and then deleted.
I got curious how did you stumble across the repo ? 😄

Also updates the requirements to be easier and with better ui/ux

https://github.com/guyluz11/infinite_horizons/issues/17#issuecomment-2093960589

**Comment by vijaykarthiktk** [comment]
I just accidentally comment on the wrong repo. But you can assign it to me. :)

**Comment by guyluz11** [comment]
😆 Ho ok
